language: generic

services:
  - docker

before_install:
  - docker pull velikodniy/xelatex

script:
  - docker run -ti -v `pwd`:/book velikodniy/xelatex bash -c "make"

deploy:
  provider: releases
  # https://github.com/settings/tokens
  # Add variable TOKEN in TravisCI settings
  api_key: $TOKEN
  file:
    - "build/programming-assignments.pdf"
  name: Версия от $(date +'%Y-%m-%d')
skip-cleanup: true
